name: utilities
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.45
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=13.0.85
  - cuda-runtime=12.1.0
  - cuda-version=13.0
  - gcc=12.4.0
  - gcc_impl_linux-64=12.4.0
  - gxx=12.4.0
  - gxx_impl_linux-64=12.4.0
  - kernel-headers_linux-64=5.14.0
  - ld_impl_linux-64=2.45
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.15.1.6
  - libcurand=10.4.0.35
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libsanitizer=12.4.0
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openssl=3.6.0
  - pip=25.3
  - python=3.11.14
  - pytorch-cuda=12.1
  - readline=8.2
  - setuptools=80.9.0
  - sysroot_linux-64=2.34
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.2.1
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - basicsr==1.4.2
      - blinker==1.9.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - choreographer==1.2.1
      - click==8.3.0
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - defusedxml==0.7.1
      - diffusers==0.31.0
      - dinov3==0.0.1
      - facexlib==0.3.0
      - ffmpeg-python==0.2.0
      - filelock==3.20.0
      - filterpy==1.4.5
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - future==1.0.0
      - gfpgan==1.3.8
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kaleido==1.1.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - logistro==2.0.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==2.12.0
      - networkx==3.5
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.11.0.86
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - protobuf==6.33.1
      - psutil==7.1.3
      - pycocotools==2.0.10
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==9.0.1
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - realesrgan==0.3.0
      - regex==2025.11.3
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - simplejson==3.20.2
      - six==1.17.0
      - submitit==1.5.3
      - supervision==0.19.0
      - sympy==1.14.0
      - tb-nightly==2.21.0a20251023
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tokenizers==0.22.1
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchmetrics==1.8.2
      - torchvision==0.24.0
      - tqdm==4.65.2
      - transformers==4.57.1
      - triton==3.5.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ultralytics==8.3.221
      - ultralytics-thop==2.0.17
      - urllib3==1.26.20
      - utilities==0.2.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - yapf==0.43.0
      - zipp==3.23.0